version: '3.8'
services:
  webservice:
    container_name: 'PHP-SERVER-SITE-BREAKING'
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SiteBreaking
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
